version: '3.8'

services:
  app:
    build: ./
    volumes:
       - ./:/var/www/app
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=development
      - PORT=3000
      - SLACK_WEBHOOK_URL=YOURWEBHOOK

    command:
       sh -c 'node index.js'